---
title: "Assignment 1 - Linear Programming"
output:
  pdf_document:
    toc: yes
    toc_depth: 5
  beamer_presentation:
    colortheme: lily
    fig_caption: no
    fig_height: 6
    fig_width: 7
    fonttheme: structurebold
    theme: Hannover
    toc: yes
  prettydoc::html_pretty:
    df_print: paged
    highlight: vignette
    theme: architect
    toc: yes
    toc_depth: 5
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '5'
  slidy_presentation:
    highlight: default
  ioslides_presentation:
    css:
    - css/fonts.css
    - css/custom.css
    - css/title-slide.css
    - css/slide-background.css
    includes:
      before_body: html/title.html
    toc: yes
    transition: default
    widescreen: yes
course: Decision Models
---

```{r setup, include=FALSE}
# Use 'verbatim = TRUE' as chunk option to show chunk code as is
require(knitr)
hook_source_def = knit_hooks$get('source')
knit_hooks$set(source = function(x, options){
  if (!is.null(options$verbatim) && options$verbatim){
    opts = gsub(",\\s*verbatim\\s*=\\s*TRUE\\s*", "", options$params.src)
    bef = sprintf('\n\n    ```{r %s}\n', opts, "\n")
    stringr::str_c(bef, paste(knitr:::indent_block(x, "    "), collapse = '\n'), "\n    ```\n")
  } else {
     hook_source_def(x, options)
  }
})
```

## The problem
A trading company is looking for a way to maximize profit per transportation of their goods. The company has a train available with 3 wagons. 

When stocking the wagons they can choose among 4 types of cargo, each with its own specifications. 
How much of each cargo type should be loaded on which wagon in order to maximize profit?

### More data
|TRAIN WAGON $j$	|WEIGHT CAPACITY (TONNE) $w_j$	|VOLUME CAPACITY ($m^2$) $s_j$|
|-----------------|-------------------------------|-----------------------------|
|(wag) 1 	        |10	                            |5000                         |
|(wag) 2	        |8	                            |4000                         |
|(wag) 3	        |12	                            |8000                         |
  



|CARGO TYPE	$i$ |AVAILABLE (TONNE) $a_i$	|VOLUME ($m^2$) $v_i$	|PROFIT (PER TONNE) $p_i$ |
|---------------|-------------------------|---------------------|-------------------------|
|(cg) 1	        |18	                      |400	                |2000                     |
|(cg) 2	        |10	                      |300	                |2500                     |
|(cg) 3	        |5	                      |200	                |5000                     |
|(cg) 4	        |20	                      |500	                |3500                     |


### The decision variables

Define the decision variables for the problem described above.

### The objective function

Define the objective function for the problem described above.

### The constraints

Define the constraints for the problem described above.

## Building the model

Build and solve the model with a suitable solver.
You might want to use the `lpSolveAPI` library.

## Sensitivity analysis

Perform the sensitivity analysis for the model solved.

# Questions about LP

1.	Can an LP model have more than one optimal solution. Is it possible for an LP model to have exactly two optimal solutions? Why or why not?

2. Are the following objective functions for an LP model equivalent? That is, if they are both used, one at a time, to solve a problem with exactly the same constraints, will the optimal values for $x_1$ and $x_2$ be the same in both cases? Why or why not?

$$
\max 2x_1+3x_2\\
\min -2x_1-3x_2
$$

3. Which of the following constraints are not linear or cannot be included as a constraint in a linear programming problem? 


a. $2 x_1+x_2-3 x_3 \geq 50$

b. $2 x_1+\sqrt{x_2} \geq 60$

c. $4 x_1- \frac{1}{2} x_2=75$

d. $\frac{3 x_1+2 x_2x-3 x_3}{x_1+x_2+x_3} \leq 0.9$

e. $3 x_1^2+7 x_2 \leq 45$

